version: "3.3"
services:
  nginx-proxy:
    # https://hub.docker.com/r/nginxproxy/nginx-proxy
    restart: always
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/discourse/shared/nginx-proxy/vhost:/etc/nginx/vhost.d
      - /var/discourse/shared/nginx-proxy/html:/usr/share/nginx/html
      - /var/discourse/shared/nginx-proxy/certs:/etc/nginx/certs

  acme:
    # https://github.com/nginx-proxy/acme-companion
    restart: always
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion
    environment:
      DEFAULT_EMAIL: ${DISCOURSE_DEVELOPER_EMAILS}
      NGINX_PROXY_CONTAINER: nginx-proxy
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/discourse/shared/nginx-proxy/acme:/etc/acme.sh
      - /var/discourse/shared/nginx-proxy/vhost:/etc/nginx/vhost.d
      - /var/discourse/shared/nginx-proxy/html:/usr/share/nginx/html
      - /var/discourse/shared/nginx-proxy/certs:/etc/nginx/certs

  db:
    image: postgres:13.8
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DISCOURSE_DB_PASSWORD}
    #   POSTGRES_USER: ${DISCOURSE_DB_USER}
      POSTGRES_DB: ${DISCOURSE_DB_NAME}
    volumes:
      - /var/discourse/shared/data:/var/lib/postgresql/data
    shm_size: ${POSTGRES_SHM_SIZE}

  redis:
    # https://hub.docker.com/_/redis
    image: redis:6.2.7
    restart: always
    container_name: redis

  web:
    image: pfaffman/discourse:plugins
    depends_on:
      - nginx-proxy
      - db
      - redis
    container_name: web_only
    command: "/sbin/boot"
    volumes:
      - /var/discourse/shared/web-only:/shared
      - /var/discourse/shared/web-only/log/var-log:/var/log
    environment:
      LANG: en_US.UTF-8
      # set these in .env file
      DISCOURSE_MAXMIND_LICENSE_KEY: ${DISCOURSE_MAXMIND_LICENSE_KEY}
      UNICORN_WORKERS: ${UNICORN_WORKERS}
      UNICORN_SIDEKIQS: ${UNICORN_SIDEKIQS}
      DISCOURSE_DB_HOSTNAME: ${DISCOURSE_DB_HOSTNAME}
      DISCOURSE_DB_USER: ${DISCOURSE_DB_USER}
      DISCOURSE_DB_NAME: ${DISCOURSE_DB_NAME}
      DISCOURSE_DB_PASSWORD: ${DISCOURSE_DB_PASSWORD}
      VIRTUAL_HOST: ${DISCOURSE_HOSTNAME}
      LETSENCRYPT_HOST: ${DISCOURSE_HOSTNAME}
      LETSENCRYPT_EMAIL: ${DISCOURSE_DEVELOPER_EMAILS}
      DISCOURSE_HOSTNAME: ${DISCOURSE_HOSTNAME}
      DISCOURSE_DEVELOPER_EMAILS: ${DISCOURSE_DEVELOPER_EMAILS}
      LETSENCRYPT_ACCOUNT_EMAIL: ${DISCOURSE_DEVELOPER_EMAILS}
      DISCOURSE_SMTP_ADDRESS: ${DISCOURSE_SMTP_ADDRESS}
      DISCOURSE_SMTP_USER_NAME: ${DISCOURSE_SMTP_USER_NAME}
      DISCOURSE_DEVELOPER_EMAILS: ${DISCOURSE_DEVELOPER_EMAILS}
      DISCOURSE_SMTP_ADDRESS: ${DISCOURSE_SMTP_ADDRESS}
      DISCOURSE_SMTP_PORT: ${DISCOURSE_SMTP_PORT}
      DISCOURSE_SMTP_PASSWORD: ${DISCOURSE_SMTP_PASSWORD}
      DISCOURSE_REDIS_HOST: ${DISCOURSE_REDIS_HOST}
      # HTTPS IS REQUIRED. Do not remove 
      DISCOURSE_FORCE_HTTPS: "true"
      
